// UI
export const CLEAR_UI = 'CLEAR_UI';
export const SET_ERROR_SNACKBAR = 'SET_ERROR_SNACKBAR';
export const SET_SUCCESS_SNACKBAR = 'SET_SUCCESS_SNACKBAR';
export const SET_COPYRIGHT = 'SET_COPYRIGHT';
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';
export const CLEAR_COPYRIGHT = 'CLEAR_COPYRIGHT'; 
export const OPEN = "OPEN";

// Projects
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

// User
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';